# EDA
## Proyecto DIABETIA
### Estancia de investigación
#### Aide Jazmín González Cruz


### 1. Carga de librerías

In [1]:
import pandas as pd
import numpy as np
import sys
import os
from os.path import dirname
from datetime import datetime

In [2]:
sys.path.append(dirname('../src'))
from src.utils import utils

In [3]:
df = pd.read_csv("../Data/Muestra.csv")
df.head(5)

newid             cx_curp  \
0  4593753CAAE51120998X96PC1  CAAE51120998X96PC1   
1  2502589CAAE51120998X96PC1  CAAE51120998X96PC1   
2  6253338CAAE51120998X96PC1  CAAE51120998X96PC1   
3  6866604CAAE51120998X96PC1  CAAE51120998X96PC1   
4  2870758CAAE51120998X96PC1  CAAE51120998X96PC1   

                                         nota_medica glucosa  colesterol  \
0                                                NaN     135         NaN   
1                                                NaN     131         NaN   
2                                                NaN     148         NaN   
3                                                NaN     NaN         NaN   
4  ELIZABET DE 59.9 AÑOS EDAD---ACUDE A EVALCUION...     126         NaN   

  trigliceridos  hdl  ldl                fecha presion_arterial  ...  \
0           NaN  NaN  NaN                  NaN           120/60  ...   
1           NaN  NaN  NaN                  NaN           130/80  ...   
2           NaN  NaN  NaN                  NaN           120/80  ...   
3           NaN  NaN  NaN                  NaN           130/70  ...   
4           NaN  NaN  NaN  SEPTIEMBRE DEL 2011              NaN  ...   

     fechas_procesadas bandera_fechas_procesadas               fuente  \
0                  NaN                       NaN  corhis_somatometria   
1                  NaN                       NaN  corhis_somatometria   
2                  NaN                       NaN  corhis_somatometria   
3                  NaN                       NaN  corhis_somatometria   
4  2011-09-01 00:00:00                       1.0                  NER   

  in_consulta fecha_nacimiento  sexo  \
0     4593753       1951-12-09     F   
1     2502589       1951-12-09     F   
2     6253338       1951-12-09     F   
3     6866604       1951-12-09     F   
4     2870758       1951-12-09     F   

                                        medicamentos  codigos_cie  \
0  FLUOXETINA CAPSULA O TABLETA CADA CAPSULA O TA...          NaN   
1  COMPLEJO B| METFORMINA, TABLETAS, METFORMINA, ...          NaN   
2  INSULINA HUMANA ACCION INTERMEDIA NPH SUSPENSI...          NaN   
3  FLUOXETINA CAPSULA O TABLETA CADA CAPSULA O TA...          NaN   
4  COMPLEJO B| PRAVASTATINA. TABLETAS. CADA TABLE...         E119   

       diagnosticos           fecha_consulta  
0               NaN  2014-12-29 09:02:48.167  
1               NaN  2010-12-21 10:58:00.640  
2               NaN  2017-10-16 10:09:10.830  
3               NaN  2018-11-02 10:22:01.733  
4  Diabetes tipo II  2011-10-08 09:47:14.953  

[5 rows x 32 columns]

## Profiling inicial
**Obteniendo información general del dataset**

- Filas y columnas

In [4]:
df.shape

(9315, 32)

- Columnas y tipo de columnas

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9315 entries, 0 to 9314
Data columns (total 32 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   newid                            9315 non-null   object 
 1   cx_curp                          9315 non-null   object 
 2   nota_medica                      2359 non-null   object 
 3   glucosa                          3926 non-null   object 
 4   colesterol                       2311 non-null   float64
 5   trigliceridos                    2373 non-null   object 
 6   hdl                              117 non-null    float64
 7   ldl                              85 non-null     float64
 8   fecha                            1924 non-null   object 
 9   presion_arterial                 5058 non-null   object 
 10  hba1c                            2075 non-null   object 
 11  hipertension                     379 non-null    object 
 12  plaquetas           

In [6]:
df.rename(columns = {'año_de_diagnostico_hipertensión':'año_de_diagnostico_hipertension'}, inplace = True)

In [7]:
df.glucosa.unique()

array(['135', '131', '148', nan, '126', '127|0', '110', '162|0', '132',
       '120', '239', '123', '178', '113', '124', '140', '128', '137',
       '199', '159', '162', '130', '212', '145', '133', '169', '218',
       '100', '156', '158', '125', '0|0', '530', '200|0', '255', '250|0',
       '80', '316', '170|0', '200', '208|0', '316|0', '130|0', '234',
       '260|0', '201', '283', '160|0', '140|0', '98', '160', '195',
       '100|130', '405|0', '158|0', '152', '309', '120|0', '217|0', '190',
       '88', '0|121', '300|0', '108', '344', '240|0', '126|0', '163',
       '163|0', '182', '182|0', '180|0', '302|0', '205', '205|0',
       '262|11', '185|0', '153', '198|0', '177|0', '291|0', '228|0',
       '400', '290|0', '193', '270|0', '100|0', '152|0', '87|0', '275',
       '344|0', '178|0', '170', '0|98', '324|0', '262|0', '192|0', '150',
       '120|9', '110|0', '108|0', '115|0', '239|351', '138', '150|0',
       '97|0', '138|0', '115', '144', '177', '164', '104|0', '116',
       '102|

In [8]:
df.colesterol.unique()

array([   nan,   0.  , 163.  , 191.  , 123.  , 250.  , 199.  , 244.  ,
       129.  , 154.  , 151.  , 139.  , 251.  , 124.  , 277.  , 195.  ,
       273.  , 202.  , 206.  ,  80.  , 287.  , 230.  , 187.  , 204.  ,
       268.  , 271.  , 220.  , 280.  , 215.  , 150.  , 200.  , 161.  ,
       172.  , 235.  , 211.  , 201.  , 193.  , 228.  , 196.  , 185.  ,
       254.  ,  93.  , 247.43, 184.  , 173.  , 288.  , 246.  , 261.  ,
       266.  , 257.  , 281.  , 177.  , 294.  , 171.  , 207.  , 231.  ,
       152.  , 108.  , 135.  , 130.  , 180.  , 166.  , 186.  , 168.  ,
       137.  , 197.  , 132.  , 189.  , 219.  , 222.  ,  95.  , 214.  ,
       351.  , 259.  , 262.  , 279.  , 128.7 , 170.  , 140.  , 181.  ,
       104.  , 119.  , 225.  , 286.  , 233.  , 241.  , 274.  , 319.  ,
       165.  , 208.  ,  88.27, 162.  , 178.  , 113.  , 242.  , 156.  ,
       198.  , 216.  ,  40.  , 143.  , 164.  , 179.  , 208.8 , 126.  ,
       192.9 , 296.  , 190.  , 188.  , 209.  , 175.  , 167.  , 159.  ,
      

In [9]:
df.trigliceridos.unique()

array([nan, '0', '274', '386', '625', '295', '384', '284', '283', '738',
       '189', '256', '604', '285', '347', '252', '319', '230', '796',
       '341', '694', '580', '752', '320', '402', '150', '426', '349',
       '205', '215', '380', '272', '329', '352', '521', '257', '278',
       '200', '158', '103', '294', '196', '153', '96', '198', '102',
       '141', '122', '156', '217', '186', '118', '129', '93', '133',
       '123', '97.7', '361', '337', '247', '264', '1332', '701', '1241',
       '250', '416', '218', '137', '148', '140', '220', '222', '111',
       '154', '182,', '182', '180', '184', '168', '181', '173', '237',
       '147', '159', '178', '424', '242', '288', '440', '160', '92',
       '485', '520', '120', '177', '166', '136', '136.8', '464', '246',
       '142', '365', '95', '104', '172', '114', '290', '63', '134', '229',
       '260', '298', '176', '76', '82', '179', '130', '135', '152', '245',
       '225', '345', '342', '268', '545', '70', '224', '296', '997',
     

In [10]:
df.hdl.unique()

array([  nan, 48.  , 47.  , 51.  , 46.  , 41.  , 37.  , 36.  , 40.  ,
       48.7 , 20.4 , 28.24, 20.  , 21.  , 22.3 , 73.  , 53.  , 44.  ,
       43.  , 35.  , 49.  , 58.  , 38.  , 56.  ])

In [11]:
df.ldl.unique()

array([  nan,  75.6, 156. , 110. , 150. , 117. , 171. , 135. ,  70.6,
        92.8,  94. , 132. ,  33. ,  22.8, 134. ,  40. ,  88. ,  66. ,
       104. , 101. , 131. , 144. , 129. ,  89. , 120. ,  91. ,  83. ])

In [12]:
df.fecha.unique()

array([nan, 'SEPTIEMBRE DEL 2011', '07  12', '37. 22',
       '19 DE AGOSTO 2015', '06 DE AGOSTO 2015', '24 DE ENERO 2016',
       '20 DE ENERO DE 2017', 'AGOSTO DE 2018', 'MARZO DE 2019',
       'NOV DE 2019', 'DIC 2013', 'MAYO DE 2019', 'MAYO DE 2016',
       '18 DE JULIO', '4 DE JULIO', '13 SEPT 2016--', '29. JUNIO DE 2017',
       'ENERO DE 2017', '15 DE JUNIO', '12 DE MARZO DE 2017',
       '6 DE MARZO', '8 DE  DE FEBRERO   DE 2018',
       '14  DE NERO DEL 1ÑO  11', '2 DE JUNIO 2014', '15 DE DIC 2015.-',
       'MARZO DE  2019', '25 MARZO DE 2019', '19 DE JULIO 2016',
       '15 DE JUNIO DE 2016', '24/01/2014', 'ENERO DE 2020',
       '20 DE OCTUBRE DE 2014', '20 12  10', '20 SEP 2016',
       '06 DE MAYO DE 2015', '13/08/12', '27/12/12', '02/07/12',
       '09/NOV2012', '30/08/12', '29 06  13', '24 DE  ENERO  2016',
       '16/03/2016', '15/03/16', '10 10 11', '29 06 10', '10/08/2011',
       '17 11  11', '17 12 12', '8 DE SEPT', '8 DE  SEPT', '12  10001',
       '37. 00', '31  

In [13]:
df.presion_arterial.unique()

array(['120/60', '130/80', '120/80', '130/70', nan, '123/65', 'NULL/NULL',
       '125/75', '120/70', '120/82', '130/75', '120/75', '120/78',
       '120/85', '110/70', '140/70', '140/90', '140/80', '110/60',
       '115/70', '110/80', '100/60', '90/60', '150/95', '130/30',
       '116/66', '130/85', '160/95', '130/78', '123/73', '120/72',
       '137/70', '133/80', '135/75', '123/70', '121/60', '125/80',
       '100/70', '125/70', '160/100', '150/70', '120/90', '160/80',
       '120/74', '100/80', '170/70', '125/68', '200/100', '157/70',
       '125/79', '136/85', '128/80', '115/60', '160/90', '170/90',
       '135/85', '150/80', '136/74', '114/78', '120/68', '180/100',
       '123/80', '150/66', '140/100', '125/85', '130/90', '140/85',
       '137/80', '122/75', '115/80', '102/75', '125/78', '123/75',
       '90/70', '150/90', '110/81', '125/76', '104/62', '122/78',
       '118/76', '137/85', '145/100', '110/69', '120/83', '110/75',
       '145/85', '135/80', '116/79', '138/88', '121

In [14]:
df.hba1c.unique()

array([nan, '0', '11.8', '8.4', '11', '8.5', '12', '10', '7', '8', '9.5',
       '9', '6.8', '8.3', '9.4', '130/80', '140/80', '5.7', '5.4', '5.2',
       '7.7', '10.8', '8.7', '6', '8.2', '5.1', '7.8', '7.5', '9.7',
       '7.9', '7.4', '7.3', '10.0', '6.09', '6009', '8.1', '6.7', '6.6',
       '6.3'], dtype=object)

In [15]:
df.hipertension.unique()

array([nan, 'HIPERTENSION ARTERIAL', 'HOPY', 'HAS', 'HIPERTENSA',
       'HIPERTENSIÓN,', 'HIEPRTENSION ARTERIAL', 'HIPERTENSION', 'HTAS',
       'HIPERTENSO', 'HIPERTENSION ARETRIAL', '.HAS',
       'HIPERTENSIÓN ARTERIAL SISTEMICA  DE 30  AÑOS DE EVOLUCION,',
       'HIPERTENSION ARTERIAL CONTROLADO, NO REFIERE SINTOMAS URINARIOS.',
       'HIPERTENSION   CON INCONTINENCIA  URINARIA    NO PORTA  LA CONTRARERERENCIA  MANIFIESTA  ULTIMOS LABOARTORIO HACE    MAS  DE  18 MESES  NO PORTA CONTRAREFERENCIA  DE UROLOGIA   PRESENTA    POLIFAGIA  POLIDIPSIA  POLIURIA  NO   CEFALEA   ACUFENOS  FOSFENOS    VISION BORROSA  EN     PERIFERIA  SOLO   VE  BIE EN EL CENTRO DE EL OJO   DERECHO PARESTESIA EN PIERNAS   A A EXPLORACION BUENA COLLORACIODN EPIEL Y TEGUMENTOS OFTALMOSCIOPIA  CON OPACIDA  LEVE  EN AMBOS OJOS  NO  SE OBSERVA OTRAS LESINES   CARDIOPULMONAR NORMAL ABDOMEN BLANDO DEPRESIBLENO DOLOROSMIEMBROSNO EDEMA  CON   VENAS VARICOSAS  PULOS NORMALES SE    ORIENTA  EN DIETA  HIPOSODICA HIPOCA

In [16]:
df.plaquetas.unique()

array([nan, '360', '439', '362', '475 000', '364 000', '394', '408 000',
       '292', '207', '270', '279', '291', '273', '293', '263', '269',
       '253000', '298', '337', '297', '294', '268', '231', '242', '219',
       '204', '215', '123', '130', '90.5', '209', '457', '119', '321',
       '122,000', '173000', '226', '175', '180', '248', '258', '260',
       '200', '613', '235', '179', '286', '253', '184', '265', '205,000',
       '317', '259 000', '296', '262,000', '136', '71', '305 000', '314',
       '278', '257', '249', '305', '329 000', '302 000', '120', '331',
       '3 09', '308', '309', '302', '250', '244', '220', '304', '198',
       '355', '352,000', '228000', '241000'], dtype=object)

In [17]:
df.creatinina.unique()

array([nan, '1', '1.4', '2.1', '1,4', '1.7', '1.6', '0.8', '1,.1', '1.5',
       '1.3', '1.1', '0.6', '0.7', '1.0', '0.9', '0.5', '0.87', '0.-5',
       '1.2', '80', '0.65', '1.54', '2.7', '4.3', '1.8', '3.2', '0.89',
       '8.6', '11', '6.6', '8.8', '7.9', '2.5', '.6', '0.50', '0.90',
       '.9', '22', '2.2', '3', '4.2'], dtype=object)

In [18]:
df.acido_urico.unique()

array([nan, '3.9', '4.8', '8.1', '5.3', '7.8', '5.6', '3.5', '5', '6.5',
       '6.4', '6.9', '5.5', '5.2', '6.8', '4.-4', '5.1', '5.0', '6.3',
       '3.7', '7.4', '7.1', '5.9', '6.1', '3.3', '3.4', '7.7', '7.5',
       '4.2', '8.7', '6.6', '9.5', '8', '8.1TCOPLESTROL', '5.7', '4.29',
       '6', '5.4', '4.4', '9.1', '6.0', '4.9', '4.0', '4.7', '15', '2.1',
       '8.4', '3.8', '4.3', '3.0', '2.7', '4.6', '7.2', '7,COLEST'],
      dtype=object)

In [19]:
df.urea.unique()

array([   nan,  55.  ,  86.  ,  89.  ,  98.  , 126.  ,  64.  ,  24.2 ,
        43.  ,  34.4 ,  31.5 , 228.  ,  19.  ,  38.  ,  30.  ,  34.7 ,
        36.2 ,  24.  ,  94.  ,  62.  ,  41.  ,  35.4 ,  51.6 , 155.4 ,
       112.  , 140.  ,  57.  ,  58.  ,  35.1 ,  46.3 ,  45.1 ,  40.8 ,
        32.  ,  22.3 ,  41.29,  35.69, 545.  ,  31.  ,  18.2 ,  46.9 ,
        47.  ,  48.  ,  44.4 ,  67.  , 114.19,  66.4 , 139.  ,  81.96,
        72.78,  22.  ,  34.  ,  33.52,  35.  ,  29.  ,  26.  ,  14.  ,
        28.  , 136.  ,  27.3 ,  30.1 ,  39.9 ])

In [20]:
df.peso.unique()

array([ 61.  ,  63.  ,  69.  ,  76.  ,    nan,  65.  ,  64.  ,  67.  ,
         0.  ,  68.  ,  61.5 ,  70.  ,  69.6 ,  60.  ,  64.5 ,  67.4 ,
        66.9 ,  60.5 ,  67.5 ,  62.  ,  67.7 ,  69.5 ,  68.3 ,  69.7 ,
        63.5 ,  86.  ,  87.  ,  91.  ,  77.5 ,  92.  ,  77.  ,  89.  ,
        94.  ,  82.  ,  92.5 ,  95.  ,  80.  ,  86.5 ,  93.  ,  78.5 ,
        84.5 ,  98.5 ,  79.  ,  83.5 ,  89.5 ,  74.5 ,  84.  ,  94.5 ,
        85.  ,  81.5 ,  71.  ,  98.  ,  74.  ,  78.  ,  82.5 ,  75.  ,
        76.5 ,  83.  ,  93.5 ,  96.5 ,  72.  ,  87.5 ,  73.  ,  88.  ,
        85.5 ,  90.  ,  75.1 ,  96.  ,  93.8 ,  97.5 ,  79.1 ,  88.5 ,
        95.5 ,  79.5 ,  81.2 ,  80.3 ,  75.5 ,  80.5 ,  79.6 , 104.  ,
        81.  ,   1.  ,  83.6 ,  86.3 ,  86.8 ,  85.8 ,  82.8 ,  85.2 ,
        60.4 ,  62.5 ,  58.  ,  59.5 ,  58.5 ,  58.3 ,  61.4 ,  57.7 ,
        60.1 ,  62.1 ,  57.5 ,  62.2 ,  61.8 ,  59.  ,  58.8 ,  60.7 ,
        60.2 ,  59.7 ,   2.  ,  83.3 ,  68.5 , 104.5 , 103.  , 105.  ,
      

In [21]:
df.altura.unique()

array([1.64, 1.67, 1.55,  nan, 1.68, 1.66, 0.  , 1.65, 1.62, 1.63, 1.61,
       1.6 , 1.52, 1.54, 1.53, 1.7 , 1.69, 1.51, 1.58, 1.56, 1.  , 1.5 ,
       1.44, 1.4 , 1.42, 1.46, 1.48, 1.75, 1.74, 1.73, 1.76, 1.79, 1.78,
       1.77, 1.49, 1.43, 1.59, 1.41, 1.45, 1.47, 1.57, 1.72, 1.82, 1.8 ,
       1.37, 1.35, 1.31, 1.3 , 1.36, 1.81, 1.84, 1.71, 1.38, 1.39])

In [22]:
df.tfg.unique()

array([nan, '40', '85.4ML', '77', '81', '68.61', '120.83', '122', '96',
       '97', '32.7', '65.37', '49.29', '62.3', '60.11', '60.95', '64.41',
       '45.13', '78.7', '72', '52.1', '46', '51', '57', '57.2', '86',
       '121', '91.12', '56.26', '133.46', '183', '137', '27.1', '71',
       '88', '117.41', '53', '80.62', '89.7', '72.47.56', '244', '249',
       '116', '84', '88.09', '77.83', '143', '64.77', '76', '98', '62.24',
       '69'], dtype=object)

In [23]:
df.imc.unique()

array([nan, '22.58', '37', '39', '35.49', '42', '40', '35. 48', '38.08',
       '36.05', '32.22', '34.76', '29.53', '29.14', '31.05', '32.81',
       '31.55', '31.62', '32.42', '31', '32.48', '30.29', '32', '33',
       '30', '26', '34.74', '28.5', '28.9', '28.65', '28.6', '34.58',
       '31.4', '33.4', '30.7', '28.2', '31.7', '32.4', '32.45', '29.7',
       '32.51', '20.44', '23.30 .', '22.93', '25.77', '18', '24.56',
       '24.02', '19.33', '32.79', '31.72', '30.52', '31.32', '30.56',
       '31.19', '30.73', '29', '30.48', '30.78', '32.7', '32.88', '33.1',
       '32.2', '33.2', '33.62', '34', '35.59', '33.74', '33.42', '35.52',
       '23', '32.85', '29.15', '25.5', '23.80', '26.31', '28.83', '32.25',
       '31.64', '31.23', '31.84', '25', '28.4', '24.13', '24.66', '28',
       '29.77', '26.35', '29.59', '25.95', '27.33', '25.33', '28.55',
       '27.88', '26.95', '27', '26.12', '25.5 N', '26.17', '25.78',
       '30.07', '29.68', '29.6', '29,08', '25,05', '30,30', '31.17',
    

In [24]:
df.año_de_diagnostico_diabetes.unique()

array([nan, '1982', '1981', '1983', '2002', '2010', '2011', '2012',
       '2013', '2009', '2000', '2018', '2014', '2006', '2015', '2001',
       '2001.,HAS', '1999', '1995', '2017', '1997', '2016', '1986',
       '1998', '2003', '300000', '2005', '1994', '1996', '1984', '2004'],
      dtype=object)

In [25]:
df.año_de_diagnostico_hipertension.unique()

array([  nan, 1997., 2009., 2016., 2018., 2000., 2010., 2012., 1999.,
       2017., 2006., 2013., 2001.])

In [26]:
df.fechas_procesadas.unique()

array([nan, '2011-09-01 00:00:00', '07 12', '37. 22', '19 DE AGOSTO 2015',
       '06 DE AGOSTO 2015', '24 DE ENERO 2016', '20 DE ENERO DE 2017',
       '2018-08-01 00:00:00', '2019-03-01 00:00:00',
       '2019-11-01 00:00:00', 'NAN', '2013-12-01 00:00:00',
       '2019-05-01 00:00:00', '2016-05-01 00:00:00', '18 DE JULIO',
       '4 DE JULIO', '13 SEPT 2016--', '2017-06-01 00:00:00',
       '2017-01-01 00:00:00', '15 DE JUNIO', '12 DE MARZO DE 2017',
       '6 DE MARZO', '8 DE DE FEBRERO DE 2018', '14 DE NERO DEL 1ÑO 11',
       '2 DE JUNIO 2014', '15 DE DIC 2015.-', '25 MARZO DE 2019',
       '19 DE JULIO 2016', '15 DE JUNIO DE 2016', '2014-01-24 00:00:00',
       '2020-01-01 00:00:00', '20 DE OCTUBRE DE 2014',
       '2010-12-20 00:00:00', '20 SEP 2016', '06 DE MAYO DE 2015',
       '2012-08-13 00:00:00', '2012-12-27 00:00:00',
       '2012-07-02 00:00:00', '09/NOV2012', '2012-08-30 00:00:00',
       '2013-06-29 00:00:00', '2016-03-16 00:00:00',
       '2016-03-15 00:00:00', '2011-

In [27]:
df.bandera_fechas_procesadas.unique()

array([nan,  1.,  0.])

In [28]:
df.fuente.unique()

array(['corhis_somatometria', 'NER', 'exphis_hc_diabetes'], dtype=object)

In [29]:
df.in_consulta.unique()

array([4593753, 2502589, 6253338, ..., 1187284, 3102755, 1013521])

In [30]:
df.fecha_nacimiento.unique()

array(['1951-12-09', '1977-06-16', '1944-02-02', '1944-05-14',
       '1940-01-01', '1951-12-29', '1955-03-21', '1963-12-31',
       '1956-10-14', '1969-04-15', '1954-05-09', '1960-07-06',
       '1968-06-23', '1933-05-01', '1964-03-29', '1961-09-04',
       '1946-11-05', '1938-09-12', '1936-06-23', '1936-08-20',
       '1934-12-29', '1964-07-05', '1964-12-15', '1969-04-11',
       '1949-04-17', '1957-03-10', '1938-11-20', '1947-09-12',
       '1964-06-29', '1958-01-01', '1967-01-20', '1948-10-04',
       '1975-03-24', '1954-06-07', '1960-06-27', '1958-12-17',
       '1940-09-30', '1961-04-30', '1973-10-06', '1969-12-20',
       '1949-12-22', '1949-08-15', '1948-07-18', '1974-04-10',
       '1951-08-12', '1960-10-28', '1963-02-13', '1968-04-08',
       '1937-11-09', '1957-12-28', '1952-11-13', '1955-08-10',
       '1949-02-15', nan, '1987-04-10'], dtype=object)

In [31]:
df.sexo.unique()

array(['F', 'M', nan], dtype=object)

In [32]:
df.medicamentos.unique()

array(['FLUOXETINA CAPSULA O TABLETA CADA CAPSULA O TABLETA CONTIENE: CLORHIDRATO DE FLUOXETINA EQUIVALENTE A 20 MG DE FLUOXETINA. ENVASE CON 14 CAPSULAS O TABLETAS.| METFORMINA TABLETA CADA TABLETA CONTIENE: CLORHIDRATO DE METFORMINA 850 MG   ENVASE CON 30 TABLETAS.| PARACETAMOL TABLETA CADA TABLETA CONTIENE: PARACETAMOL 500 MG ENVASE CON 10  TABLETAS.| AMBROXOL COMPRIMIDO CADA COMPRIMIDO CONTIENE: CLORHIDRATO DE AMBROXOL 30 MG   ENVASE CON 20 COMPRIMIDOS.',
       'COMPLEJO B| METFORMINA, TABLETAS, METFORMINA, CLORHIDRATO DE, CADA TABLETA CONTIENE: 850 MILIGRAMOS.',
       'INSULINA HUMANA ACCION INTERMEDIA NPH SUSPENSION INYECTABLE ACCION INTERMEDIA  NPH CADA ML CONTIENE: INSULINA HUMANA ISOFANA (ORIGEN ADN RECOMBINANTE) 100 UI  O INSULINA ZINC ISOFANA HUMANA (ORIGEN ADN RECOMBINANTE) 100 UI ENVASE CON UN| BEZAFIBRATO TABLETA CADA TABLETA CONTIENE: BEZAFIBRATO 200 MG ENVASE CON 30  TABLETAS.| LOSARTAN GRAGEA O COMPRIMIDO RECUBIERTO CADA GRAGEA O COMPRIMIDO RECUBIERTO   CONTIENE: LOS

In [33]:
df.codigos_cie.unique()

array([nan, 'E119', 'E119      , I10X', 'J068', 'E11X', 'Z713',
       'E119      , M790      , K295      , E039      , J988',
       'E109      , I10X      , M069', 'E119      , H491',
       'E109      , I10X',
       'E119      , E109      , M069      , F329      , Z911', 'E109',
       'E66X      , E039      , F419      , M069',
       'E109      , M069      , F329      , G479',
       'E109      , M790      , M069      , E66X      , K589',
       'E105      , E039',
       'E11X      , E039      , K297      , M069      , E66X',
       'E107      , M069      , E039',
       'E11X      , I10X      , F329      , J029',
       'E10X      , M069      , I10X      , E039      , M790      , K295      , G431',
       'E117', 'E109      , M790      , M069',
       'E11X      , I10X      , M069', 'E109      , M069',
       'E11X      , M069      , K295      , I872      , J040      , R51X',
       'D649', 'E105', 'E109      , I10X      , F412',
       'E109      , M069      , I99X',
       'E

In [34]:
df.diagnosticos.unique()

array([nan, 'Diabetes tipo II', 'Diabetes tipo II, Hipertension arterial',
       'Faringoamigdalitis aguda',
       'Diabetes mellitus no insulinodependiente',
       'Diabetes consulta y supervisión de la dieta',
       'Diabetes tipo II, Fibromialgia , Gastritis cronica, Hipotiroidismo, Infección respiratoria',
       'Diabetes tipo I, Hipertension arterial, Artritis reumatoide',
       'Diabetes mellitus no insulinodependiente,sin mencion de complicacion, Parálisis nervio craneal iv par o patético',
       'Diabetes tipo I, Hipertension arterial',
       'Diabetes tipo II, Diabetes tipo I, Artritis reumatoide , Trastorno depresivo (ver también depresión) , Historia incumplimiento del régimen o tratamiento médico',
       'Diabetes insulinodependiente',
       'Obesidad, Hipotiroidismo, Ansiedad , Artritis reumatoide',
       'Diabetes tipo I, Artritis reumatoide , Trastorno depresivo (ver también depresión) , Trastorno sueño',
       'Diabetes tipo I, Fibromialgia , Artritis reumat

In [35]:
df.fecha_consulta.unique()

array(['2014-12-29 09:02:48.167', '2010-12-21 10:58:00.640',
       '2017-10-16 10:09:10.830', ..., '2012-05-28 17:23:44.613',
       '2020-07-07 16:38:16.830', '2011-07-20 18:52:01.410'], dtype=object)

## Transformación de datos

Glucosa

In [36]:
# concat columns by separator
#df['presion_arterial'].str.cat(df[['sistolica', 'diastolica']], sep='/')
# split column into multiple columns by delimiter 
df_g = df['glucosa'].str.split('|', expand=True)
df_g.columns = ['glucosa1', 'glucosa2']
df["glucosa1"] = df_g["glucosa1"]
df["glucosa2"] = df_g["glucosa2"]
df.head(5)

newid             cx_curp  \
0  4593753CAAE51120998X96PC1  CAAE51120998X96PC1   
1  2502589CAAE51120998X96PC1  CAAE51120998X96PC1   
2  6253338CAAE51120998X96PC1  CAAE51120998X96PC1   
3  6866604CAAE51120998X96PC1  CAAE51120998X96PC1   
4  2870758CAAE51120998X96PC1  CAAE51120998X96PC1   

                                         nota_medica glucosa  colesterol  \
0                                                NaN     135         NaN   
1                                                NaN     131         NaN   
2                                                NaN     148         NaN   
3                                                NaN     NaN         NaN   
4  ELIZABET DE 59.9 AÑOS EDAD---ACUDE A EVALCUION...     126         NaN   

  trigliceridos  hdl  ldl                fecha presion_arterial  ...  \
0           NaN  NaN  NaN                  NaN           120/60  ...   
1           NaN  NaN  NaN                  NaN           130/80  ...   
2           NaN  NaN  NaN                  NaN           120/80  ...   
3           NaN  NaN  NaN                  NaN           130/70  ...   
4           NaN  NaN  NaN  SEPTIEMBRE DEL 2011              NaN  ...   

                fuente in_consulta fecha_nacimiento sexo  \
0  corhis_somatometria     4593753       1951-12-09    F   
1  corhis_somatometria     2502589       1951-12-09    F   
2  corhis_somatometria     6253338       1951-12-09    F   
3  corhis_somatometria     6866604       1951-12-09    F   
4                  NER     2870758       1951-12-09    F   

                                        medicamentos  codigos_cie  \
0  FLUOXETINA CAPSULA O TABLETA CADA CAPSULA O TA...          NaN   
1  COMPLEJO B| METFORMINA, TABLETAS, METFORMINA, ...          NaN   
2  INSULINA HUMANA ACCION INTERMEDIA NPH SUSPENSI...          NaN   
3  FLUOXETINA CAPSULA O TABLETA CADA CAPSULA O TA...          NaN   
4  COMPLEJO B| PRAVASTATINA. TABLETAS. CADA TABLE...         E119   

       diagnosticos           fecha_consulta glucosa1 glucosa2  
0               NaN  2014-12-29 09:02:48.167      135     None  
1               NaN  2010-12-21 10:58:00.640      131     None  
2               NaN  2017-10-16 10:09:10.830      148     None  
3               NaN  2018-11-02 10:22:01.733      NaN      NaN  
4  Diabetes tipo II  2011-10-08 09:47:14.953      126     None  

[5 rows x 34 columns]

In [37]:
df['trigliceridos'] = df['trigliceridos'].replace(',', '', regex=True)
df['trigliceridos'] = df['trigliceridos'].astype(float)
df.trigliceridos.unique()

array([     nan,    0.   ,  274.   ,  386.   ,  625.   ,  295.   ,
        384.   ,  284.   ,  283.   ,  738.   ,  189.   ,  256.   ,
        604.   ,  285.   ,  347.   ,  252.   ,  319.   ,  230.   ,
        796.   ,  341.   ,  694.   ,  580.   ,  752.   ,  320.   ,
        402.   ,  150.   ,  426.   ,  349.   ,  205.   ,  215.   ,
        380.   ,  272.   ,  329.   ,  352.   ,  521.   ,  257.   ,
        278.   ,  200.   ,  158.   ,  103.   ,  294.   ,  196.   ,
        153.   ,   96.   ,  198.   ,  102.   ,  141.   ,  122.   ,
        156.   ,  217.   ,  186.   ,  118.   ,  129.   ,   93.   ,
        133.   ,  123.   ,   97.7  ,  361.   ,  337.   ,  247.   ,
        264.   , 1332.   ,  701.   , 1241.   ,  250.   ,  416.   ,
        218.   ,  137.   ,  148.   ,  140.   ,  220.   ,  222.   ,
        111.   ,  154.   ,  182.   ,  180.   ,  184.   ,  168.   ,
        181.   ,  173.   ,  237.   ,  147.   ,  159.   ,  178.   ,
        424.   ,  242.   ,  288.   ,  440.   ,  160.   ,   92.

In [38]:
df.count()

newid                              9315
cx_curp                            9315
nota_medica                        2359
glucosa                            3926
colesterol                         2311
trigliceridos                      2373
hdl                                 117
ldl                                  85
fecha                              1924
presion_arterial                   5058
hba1c                              2075
hipertension                        379
plaquetas                           258
creatinina                          527
acido_urico                         250
urea                                195
peso                               4995
altura                             4993
tfg                                 189
imc                                 495
año_de_diagnostico_diabetes         298
año_de_diagnostico_hipertension     161
fechas_procesadas                  2359
bandera_fechas_procesadas          2359
fuente                             9315


In [39]:
df['presion_arterial'] =  np.where(df.hba1c.str.contains("/") & df['presion_arterial'].isnull(), \
                                               df['hba1c'],\
                                               df['presion_arterial'])

df['hba1c'] =  np.where(df.hba1c.str.contains("/"), \
                                               np.nan, \
                                               df['hba1c'])

In [40]:
df.count()

newid                              9315
cx_curp                            9315
nota_medica                        2359
glucosa                            3926
colesterol                         2311
trigliceridos                      2373
hdl                                 117
ldl                                  85
fecha                              1924
presion_arterial                   5061
hba1c                              2072
hipertension                        379
plaquetas                           258
creatinina                          527
acido_urico                         250
urea                                195
peso                               4995
altura                             4993
tfg                                 189
imc                                 495
año_de_diagnostico_diabetes         298
año_de_diagnostico_hipertension     161
fechas_procesadas                  2359
bandera_fechas_procesadas          2359
fuente                             9315


Dividiendo presión en sistólica y diastólica

In [41]:
# concat columns by separator
#df['presion_arterial'].str.cat(df[['sistolica', 'diastolica']], sep='/')
# split column into multiple columns by delimiter 
df_pa = df['presion_arterial'].str.split('/', expand=True)
df_pa.columns = ['sistolica', 'diastolica']
df["sistolica"] = df_pa["sistolica"]
df["diastolica"] = df_pa["diastolica"]
df.head(5)

newid             cx_curp  \
0  4593753CAAE51120998X96PC1  CAAE51120998X96PC1   
1  2502589CAAE51120998X96PC1  CAAE51120998X96PC1   
2  6253338CAAE51120998X96PC1  CAAE51120998X96PC1   
3  6866604CAAE51120998X96PC1  CAAE51120998X96PC1   
4  2870758CAAE51120998X96PC1  CAAE51120998X96PC1   

                                         nota_medica glucosa  colesterol  \
0                                                NaN     135         NaN   
1                                                NaN     131         NaN   
2                                                NaN     148         NaN   
3                                                NaN     NaN         NaN   
4  ELIZABET DE 59.9 AÑOS EDAD---ACUDE A EVALCUION...     126         NaN   

   trigliceridos  hdl  ldl                fecha presion_arterial  ...  \
0            NaN  NaN  NaN                  NaN           120/60  ...   
1            NaN  NaN  NaN                  NaN           130/80  ...   
2            NaN  NaN  NaN                  NaN           120/80  ...   
3            NaN  NaN  NaN                  NaN           130/70  ...   
4            NaN  NaN  NaN  SEPTIEMBRE DEL 2011              NaN  ...   

  fecha_nacimiento sexo                                       medicamentos  \
0       1951-12-09    F  FLUOXETINA CAPSULA O TABLETA CADA CAPSULA O TA...   
1       1951-12-09    F  COMPLEJO B| METFORMINA, TABLETAS, METFORMINA, ...   
2       1951-12-09    F  INSULINA HUMANA ACCION INTERMEDIA NPH SUSPENSI...   
3       1951-12-09    F  FLUOXETINA CAPSULA O TABLETA CADA CAPSULA O TA...   
4       1951-12-09    F  COMPLEJO B| PRAVASTATINA. TABLETAS. CADA TABLE...   

  codigos_cie      diagnosticos           fecha_consulta  glucosa1  glucosa2  \
0         NaN               NaN  2014-12-29 09:02:48.167       135      None   
1         NaN               NaN  2010-12-21 10:58:00.640       131      None   
2         NaN               NaN  2017-10-16 10:09:10.830       148      None   
3         NaN               NaN  2018-11-02 10:22:01.733       NaN       NaN   
4        E119  Diabetes tipo II  2011-10-08 09:47:14.953       126      None   

  sistolica diastolica  
0       120         60  
1       130         80  
2       120         80  
3       130         70  
4       NaN        NaN  

[5 rows x 36 columns]

In [42]:
df['hba1c'] = df['hba1c'].astype(float)
df.hba1c.unique()

array([      nan, 0.000e+00, 1.180e+01, 8.400e+00, 1.100e+01, 8.500e+00,
       1.200e+01, 1.000e+01, 7.000e+00, 8.000e+00, 9.500e+00, 9.000e+00,
       6.800e+00, 8.300e+00, 9.400e+00, 5.700e+00, 5.400e+00, 5.200e+00,
       7.700e+00, 1.080e+01, 8.700e+00, 6.000e+00, 8.200e+00, 5.100e+00,
       7.800e+00, 7.500e+00, 9.700e+00, 7.900e+00, 7.400e+00, 7.300e+00,
       6.090e+00, 6.009e+03, 8.100e+00, 6.700e+00, 6.600e+00, 6.300e+00])

In [43]:
df['plaquetas'] = df['plaquetas'].replace(',', '', regex=True)
df['plaquetas'] = df['plaquetas'].replace(' ', '', regex=True)
df['plaquetas'] = df['plaquetas'].astype(float)
df.plaquetas.unique()

array([     nan, 3.60e+02, 4.39e+02, 3.62e+02, 4.75e+05, 3.64e+05,
       3.94e+02, 4.08e+05, 2.92e+02, 2.07e+02, 2.70e+02, 2.79e+02,
       2.91e+02, 2.73e+02, 2.93e+02, 2.63e+02, 2.69e+02, 2.53e+05,
       2.98e+02, 3.37e+02, 2.97e+02, 2.94e+02, 2.68e+02, 2.31e+02,
       2.42e+02, 2.19e+02, 2.04e+02, 2.15e+02, 1.23e+02, 1.30e+02,
       9.05e+01, 2.09e+02, 4.57e+02, 1.19e+02, 3.21e+02, 1.22e+05,
       1.73e+05, 2.26e+02, 1.75e+02, 1.80e+02, 2.48e+02, 2.58e+02,
       2.60e+02, 2.00e+02, 6.13e+02, 2.35e+02, 1.79e+02, 2.86e+02,
       2.53e+02, 1.84e+02, 2.65e+02, 2.05e+05, 3.17e+02, 2.59e+05,
       2.96e+02, 2.62e+05, 1.36e+02, 7.10e+01, 3.05e+05, 3.14e+02,
       2.78e+02, 2.57e+02, 2.49e+02, 3.05e+02, 3.29e+05, 3.02e+05,
       1.20e+02, 3.31e+02, 3.09e+02, 3.08e+02, 3.02e+02, 2.50e+02,
       2.44e+02, 2.20e+02, 3.04e+02, 1.98e+02, 3.55e+02, 3.52e+05,
       2.28e+05, 2.41e+05])

In [44]:
df['creatinina'] = df['creatinina'].replace(',', '', regex=True)
df['creatinina'] = df['creatinina'].replace(' ', '', regex=True)
df['creatinina'] = df['creatinina'].replace('-', '', regex=True)
df['creatinina'] = df['creatinina'].astype(float)
df.creatinina.unique()

array([  nan,  1.  ,  1.4 ,  2.1 , 14.  ,  1.7 ,  1.6 ,  0.8 ,  1.1 ,
        1.5 ,  1.3 ,  0.6 ,  0.7 ,  0.9 ,  0.5 ,  0.87,  1.2 , 80.  ,
        0.65,  1.54,  2.7 ,  4.3 ,  1.8 ,  3.2 ,  0.89,  8.6 , 11.  ,
        6.6 ,  8.8 ,  7.9 ,  2.5 , 22.  ,  2.2 ,  3.  ,  4.2 ])

In [45]:
df['acido_urico'] = df['acido_urico'].replace(',', '', regex=True)
df['acido_urico'] = df['acido_urico'].replace(' ', '', regex=True)
df['acido_urico'] = df['acido_urico'].replace('-', '', regex=True)
df['acido_urico'] = df['acido_urico'].str.replace('[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z]', '')
#df['acido_urico']  = df['acido_urico'].map(utils.dejar_solo_cifras)
df['acido_urico'] = df['acido_urico'].astype(float)
df.acido_urico.unique()

array([  nan,  3.9 ,  4.8 ,  8.1 ,  5.3 ,  7.8 ,  5.6 ,  3.5 ,  5.  ,
        6.5 ,  6.4 ,  6.9 ,  5.5 ,  5.2 ,  6.8 ,  4.4 ,  5.1 ,  6.3 ,
        3.7 ,  7.4 ,  7.1 ,  5.9 ,  6.1 ,  3.3 ,  3.4 ,  7.7 ,  7.5 ,
        4.2 ,  8.7 ,  6.6 ,  9.5 ,  8.  ,  5.7 ,  4.29,  6.  ,  5.4 ,
        9.1 ,  4.9 ,  4.  ,  4.7 , 15.  ,  2.1 ,  8.4 ,  3.8 ,  4.3 ,
        3.  ,  2.7 ,  4.6 ,  7.2 ,  7.  ])

In [46]:
df['tfg'] = df['tfg'].replace(',', '', regex=True)
df['tfg'] = df['tfg'].replace(' ', '', regex=True)
df['tfg'] = df['tfg'].replace('-', '', regex=True)
df['tfg']=df['tfg'].astype(str)
df['tfg'] = df['tfg'].str.replace('[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z]', '')

In [47]:
for i in range(len(df['tfg'])):
    x = df['tfg'][i]
    if(x.count(".")>1):
        print(df['tfg'][i])
        print(df['tfg'][i][:5])
        df['tfg'][i] = df['tfg'][i][:5]
        
df['tfg'] = df['tfg'].astype(float)
df.tfg.unique()

72.47.56
72.47


/home/aide/.pyenv/versions/itam_intro_to_ds/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


array([   nan,  40.  ,  85.4 ,  77.  ,  81.  ,  68.61, 120.83, 122.  ,
        96.  ,  97.  ,  32.7 ,  65.37,  49.29,  62.3 ,  60.11,  60.95,
        64.41,  45.13,  78.7 ,  72.  ,  52.1 ,  46.  ,  51.  ,  57.  ,
        57.2 ,  86.  , 121.  ,  91.12,  56.26, 133.46, 183.  , 137.  ,
        27.1 ,  71.  ,  88.  , 117.41,  53.  ,  80.62,  89.7 ,  72.47,
       244.  , 249.  , 116.  ,  84.  ,  88.09,  77.83, 143.  ,  64.77,
        76.  ,  98.  ,  62.24,  69.  ])

In [48]:
df['imc'] = df['imc'].replace(',', '', regex=True)
df['imc'] = df['imc'].replace(' ', '', regex=True)
df['imc'] = df['imc'].replace('-', '', regex=True)
df['imc'] = df['imc'].str.replace('[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z]', '')
df['imc']=df['imc'].astype(str)
for i in range(len(df['imc'])):
    x = df['imc'][i]
    if(x.count(".")>1):
        df['imc'][i] = df['imc'][i][:5]
df['imc'] = df['imc'].astype(float)
df.imc.unique()

/home/aide/.pyenv/versions/itam_intro_to_ds/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':


array([      nan, 2.258e+01, 3.700e+01, 3.900e+01, 3.549e+01, 4.200e+01,
       4.000e+01, 3.548e+01, 3.808e+01, 3.605e+01, 3.222e+01, 3.476e+01,
       2.953e+01, 2.914e+01, 3.105e+01, 3.281e+01, 3.155e+01, 3.162e+01,
       3.242e+01, 3.100e+01, 3.248e+01, 3.029e+01, 3.200e+01, 3.300e+01,
       3.000e+01, 2.600e+01, 3.474e+01, 2.850e+01, 2.890e+01, 2.865e+01,
       2.860e+01, 3.458e+01, 3.140e+01, 3.340e+01, 3.070e+01, 2.820e+01,
       3.170e+01, 3.240e+01, 3.245e+01, 2.970e+01, 3.251e+01, 2.044e+01,
       2.330e+01, 2.293e+01, 2.577e+01, 1.800e+01, 2.456e+01, 2.402e+01,
       1.933e+01, 3.279e+01, 3.172e+01, 3.052e+01, 3.132e+01, 3.056e+01,
       3.119e+01, 3.073e+01, 2.900e+01, 3.048e+01, 3.078e+01, 3.270e+01,
       3.288e+01, 3.310e+01, 3.220e+01, 3.320e+01, 3.362e+01, 3.400e+01,
       3.559e+01, 3.374e+01, 3.342e+01, 3.552e+01, 2.300e+01, 3.285e+01,
       2.915e+01, 2.550e+01, 2.380e+01, 2.631e+01, 2.883e+01, 3.225e+01,
       3.164e+01, 3.123e+01, 3.184e+01, 2.500e+01, 

In [49]:
df.tfg.unique()

array([   nan,  40.  ,  85.4 ,  77.  ,  81.  ,  68.61, 120.83, 122.  ,
        96.  ,  97.  ,  32.7 ,  65.37,  49.29,  62.3 ,  60.11,  60.95,
        64.41,  45.13,  78.7 ,  72.  ,  52.1 ,  46.  ,  51.  ,  57.  ,
        57.2 ,  86.  , 121.  ,  91.12,  56.26, 133.46, 183.  , 137.  ,
        27.1 ,  71.  ,  88.  , 117.41,  53.  ,  80.62,  89.7 ,  72.47,
       244.  , 249.  , 116.  ,  84.  ,  88.09,  77.83, 143.  ,  64.77,
        76.  ,  98.  ,  62.24,  69.  ])

In [50]:
df['año_de_diagnostico_diabetes'] = df['año_de_diagnostico_diabetes'].replace(',', '', regex=True)
df['año_de_diagnostico_diabetes'] = df['año_de_diagnostico_diabetes'].replace(' ', '', regex=True)
df['año_de_diagnostico_diabetes'] = df['año_de_diagnostico_diabetes'].replace('-', '', regex=True)
df['año_de_diagnostico_diabetes'] = df['año_de_diagnostico_diabetes'].replace('NA', np.nan, regex=True)
df['año_de_diagnostico_diabetes'] = df['año_de_diagnostico_diabetes'].astype(str)
df['año_de_diagnostico_diabetes'] = df['año_de_diagnostico_diabetes'].str.replace('[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z]', '')

df['año_de_diagnostico_diabetes'] = df['año_de_diagnostico_diabetes'].astype(np.float).astype("Int32")
for i in range(len(df['año_de_diagnostico_diabetes'])):
    x = df['año_de_diagnostico_diabetes'][i]
    if pd.isna(x):
        x=x
    else:
        print(x)
        if(x > 2022):
            df['año_de_diagnostico_diabetes'][i] = np.nan        
df.año_de_diagnostico_diabetes.unique()

1982
1981
1982
1982
1983
2002
2002
2002
2002
2002
2002
2002
2002
2002
2002
2002
2010
2010
2010
2010
2011
2012
2010
2011
2011
2010
2012
2012
2011
2011
2011
2012
2011
2010
2010
2013
2013
2012
2012
2013
2013
2013
2013
2013
2009
2013
2013
2013
2012
2012
2013
2013
2013
2013
2012
2012
2013
2013
2013
2013
2013
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2000
2018
2014
2006
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2010
2015
2010
2010
2010
2018
2000
2000
2001
2001
2001
2001
2001
2001
2011
2001
2001
2001
2001
2001
2001
2001
2001
2001
2001
2001
2001
1999
2001
2001
2000
1995
2000
2000
2000
2000
2000
2000
2000
2017
2000
2000
2000
2000
2000
1995
2000
1995
1995
1995
1995
1995
1995
1997
2016
2015
2015
2015
1986
2013
2013
2013
1998
2003
2000
2000
2014
2014
2000
2014
2000
2000
2014
2014
2014
2014
2014
2017
300000
2005
2017
2017
2017
2017
1999
1999
1999
1999
199

<IntegerArray>
[<NA>, 1982, 1981, 1983, 2002, 2010, 2011, 2012, 2013, 2009, 2000, 2018, 2014,
 2006, 2015, 2001, 1999, 1995, 2017, 1997, 2016, 1986, 1998, 2003, 2005, 1994,
 1996, 1984, 2004]
Length: 29, dtype: Int32

In [51]:
df['fechas_procesadas2'] =df['fechas_procesadas']

In [52]:
df['fechas_procesadas2']=df['fechas_procesadas2'].astype(str)
print(df[df["fechas_procesadas2"].apply(lambda x: len(x) > 100)][['nota_medica','fechas_procesadas2','glucosa']])
b = df[df["fechas_procesadas2"].apply(lambda x: len(x) > 100)][['nota_medica','fechas_procesadas2']]
b

                                            nota_medica  \
1449  DIABETIMSS MATUTINO ACUDE A CONTROL MENSUAL PA...   
1505  DIABETIMSS MATUTINO ACUDE A CONTROL MENSUAL PA...   

                                     fechas_procesadas2 glucosa  
1449  31 07 14 GLUCOSA 130 DESCONTROLADA, PACIENTE Q...     NaN  
1505  06 01 14 GLUCOSA 96 CONTROLADA, PACIENTE CON B...     NaN  


nota_medica  \
1449  DIABETIMSS MATUTINO ACUDE A CONTROL MENSUAL PA...   
1505  DIABETIMSS MATUTINO ACUDE A CONTROL MENSUAL PA...   

                                     fechas_procesadas2  
1449  31 07 14 GLUCOSA 130 DESCONTROLADA, PACIENTE Q...  
1505  06 01 14 GLUCOSA 96 CONTROLADA, PACIENTE CON B...

In [53]:
np.where(b.fechas_procesadas2.str.len() > 50, \
         b['fechas_procesadas2'].astype(str).str[:8],\
         b['fechas_procesadas2'])

array(['31 07 14', '06 01 14'], dtype=object)

In [54]:
np.where(b.fechas_procesadas2.str.len() > 50, \
         "20"+b['fechas_procesadas2'].astype(str).str[6:8]+"-"+
              b['fechas_procesadas2'].astype(str).str[3:5]+"-"+
              b['fechas_procesadas2'].astype(str).str[0:2],\
         b['fechas_procesadas2'])

array(['2014-07-31', '2014-01-06'], dtype=object)

In [55]:
df['fechas_procesadas2'] = np.where(df.fechas_procesadas2.str.len() > 50, \
                                    "20"+df['fechas_procesadas2'].astype(str).str[6:8]+"-"+
                                         df['fechas_procesadas2'].astype(str).str[3:5]+"-"+
                                         df['fechas_procesadas2'].astype(str).str[0:2],\
                                         df['fechas_procesadas2'])

In [56]:
df.fechas_procesadas2.unique()

array(['nan', '2011-09-01 00:00:00', '07 12', '37. 22',
       '19 DE AGOSTO 2015', '06 DE AGOSTO 2015', '24 DE ENERO 2016',
       '20 DE ENERO DE 2017', '2018-08-01 00:00:00',
       '2019-03-01 00:00:00', '2019-11-01 00:00:00', 'NAN',
       '2013-12-01 00:00:00', '2019-05-01 00:00:00',
       '2016-05-01 00:00:00', '18 DE JULIO', '4 DE JULIO',
       '13 SEPT 2016--', '2017-06-01 00:00:00', '2017-01-01 00:00:00',
       '15 DE JUNIO', '12 DE MARZO DE 2017', '6 DE MARZO',
       '8 DE DE FEBRERO DE 2018', '14 DE NERO DEL 1ÑO 11',
       '2 DE JUNIO 2014', '15 DE DIC 2015.-', '25 MARZO DE 2019',
       '19 DE JULIO 2016', '15 DE JUNIO DE 2016', '2014-01-24 00:00:00',
       '2020-01-01 00:00:00', '20 DE OCTUBRE DE 2014',
       '2010-12-20 00:00:00', '20 SEP 2016', '06 DE MAYO DE 2015',
       '2012-08-13 00:00:00', '2012-12-27 00:00:00',
       '2012-07-02 00:00:00', '09/NOV2012', '2012-08-30 00:00:00',
       '2013-06-29 00:00:00', '2016-03-16 00:00:00',
       '2016-03-15 00:00:00

In [57]:
df['fechas_procesadas2'] = df['fechas_procesadas2'].astype(str)
df['fechas_procesadas2'] = df['fechas_procesadas2'].replace(' DE ', '/', regex=True)
df['fechas_procesadas2'] = df['fechas_procesadas2'].replace(' DEL ', '/', regex=True)
df['fechas_procesadas2'] = df['fechas_procesadas2'].replace('10 / 12/EDAD, CON DX/1', np.nan, regex=True)
df['fechas_procesadas2'] = df['fechas_procesadas2'].replace('ABRIL/2012----PACIENTE', np.nan, regex=True)
df['fechas_procesadas2'] = df['fechas_procesadas2'].replace('ENERO 2019---------------CONSIENTE', np.nan, regex=True)
df['fechas_procesadas2'] = df['fechas_procesadas2'].astype(str)
df[df["fechas_procesadas2"].apply(lambda x: len(x) > 19)][['fechas_procesadas2','glucosa']]

fechas_procesadas2 glucosa
1511  05 11 14 GLUCOSA 353     NaN
2540  04 01 17 GLUCOSA 124     NaN
2665  16 12 16 GLUCOSA 148     NaN
8691  14 03 16 GLUCOSA 255     NaN

In [58]:
df['fechas_procesadas2'] = df['fechas_procesadas2'].astype(str)
for i in range(len(df['fechas_procesadas2'])):
    x = df['fechas_procesadas2'][i]
    if ('GLUCOSA' in x) & (len(x) > 19):
        print("20"+x[6:8]+"-"+x[3:5]+"-"+x[0:2])
        """df['fechas_procesadas2'][i] = "20"+df['fechas_procesadas2'][i].astype(str).str[6:8]+"-"+
                                           df['fechas_procesadas2'][i].astype(str).str[3:5]+"-"+
                                           df['fechas_procesadas2'][i].astype(str).str[0:2]"""
        print(x[17:len(x)])
        y = "20"+x[6:8]+"-"+x[3:5]+"-"+x[0:2]
        print(datetime.strptime(y, '%Y-%m-%d')) 

2014-11-05
353
2014-11-05 00:00:00
2017-01-04
124
2017-01-04 00:00:00
2016-12-16
148
2016-12-16 00:00:00
2016-03-14
255
2016-03-14 00:00:00


In [59]:
for i in range(len(df['fechas_procesadas2'])):
    x = df['fechas_procesadas2'][i]
    if ('GLUCOSA' in x) & (len(x) > 19):
        y = "20"+x[6:8]+"-"+x[3:5]+"-"+x[0:2]
        df['fechas_procesadas2'][i] = datetime.strptime(y, '%Y-%m-%d') 
        df['glucosa1'][i] = x[17:len(x)]

/home/aide/.pyenv/versions/itam_intro_to_ds/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/home/aide/.pyenv/versions/itam_intro_to_ds/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [60]:
df['fechas_procesadas2'] = df['fechas_procesadas2'].astype(str)
df['fechas_procesadas2'] = df['fechas_procesadas2'].replace('DE ', '/', regex=True)
#df[df["fechas_procesadas2"].apply(lambda x: len(x) != 19 & x is not None)][['fechas_procesadas2']]
df.fechas_procesadas2.unique()

array(['nan', '2011-09-01 00:00:00', '07 12', '37. 22', '19/AGOSTO 2015',
       '06/AGOSTO 2015', '24/ENERO 2016', '20/ENERO/2017',
       '2018-08-01 00:00:00', '2019-03-01 00:00:00',
       '2019-11-01 00:00:00', 'NAN', '2013-12-01 00:00:00',
       '2019-05-01 00:00:00', '2016-05-01 00:00:00', '18/JULIO',
       '4/JULIO', '13 SEPT 2016--', '2017-06-01 00:00:00',
       '2017-01-01 00:00:00', '15/JUNIO', '12/MARZO/2017', '6/MARZO',
       '8//FEBRERO/2018', '14/NERO/1ÑO 11', '2/JUNIO 2014',
       '15/DIC 2015.-', '25 MARZO/2019', '19/JULIO 2016', '15/JUNIO/2016',
       '2014-01-24 00:00:00', '2020-01-01 00:00:00', '20/OCTUBRE/2014',
       '2010-12-20 00:00:00', '20 SEP 2016', '06/MAYO/2015',
       '2012-08-13 00:00:00', '2012-12-27 00:00:00',
       '2012-07-02 00:00:00', '09/NOV2012', '2012-08-30 00:00:00',
       '2013-06-29 00:00:00', '2016-03-16 00:00:00',
       '2016-03-15 00:00:00', '2011-10-10 00:00:00',
       '2010-06-29 00:00:00', '2011-08-10 00:00:00',
       '2011-

In [61]:
c = df[df["fechas_procesadas2"].str.contains("/")][['fechas_procesadas2']]
c = pd.DataFrame(c)
c

fechas_procesadas2
128      19/AGOSTO 2015
129      06/AGOSTO 2015
135       24/ENERO 2016
136       20/ENERO/2017
141       20/ENERO/2017
...                 ...
9138            10 / 12
9140             7 / 12
9148            10 / 12
9155            20 / 20
9156             3 / 12

[652 rows x 1 columns]

In [62]:
c = np.where(c.fechas_procesadas2.str.contains("/"), \
         c['fechas_procesadas2'].replace(' ', '/', regex=True).\
                                replace('//', '/', regex=True).\
                                replace('ENERO', '01', regex=True).\
                                replace('FEBRERO', '02', regex=True).\
                                replace('MARZO', '03', regex=True).\
                                replace('ABRIL', '04', regex=True).\
                                replace('MAYO', '05', regex=True).\
                                replace('JUNIO', '06', regex=True).\
                                replace('JULIO', '07', regex=True).\
                                replace('AGOSTO', '08', regex=True).\
                                replace('SEPTIEMBRE', '09', regex=True).\
                                replace('OCTUBRE', '10', regex=True).\
                                replace('NOVIEMBRE', '11', regex=True).\
                                replace('DICIEMBRE', '12', regex=True).\
                                replace('//', '/', regex=True),\
         c['fechas_procesadas2'])
c = pd.DataFrame(c)
c.columns = ['fechas_procesadas2']
c

fechas_procesadas2
0           19/08/2015
1           06/08/2015
2           24/01/2016
3           20/01/2017
4           20/01/2017
..                 ...
647              10/12
648               7/12
649              10/12
650              20/20
651               3/12

[652 rows x 1 columns]

In [63]:
for i in range(len(c['fechas_procesadas2'])):
    x = c['fechas_procesadas2'][i]
    counter = x.count('/')
    if (counter == 2 and len(x) == 10) and x[6:10].isnumeric() and x[3:5].isnumeric() and x[0:2].isnumeric():
        y = x[6:10]+"-"+x[3:5]+"-"+x[0:2]
        print(y)
        #df['fechas_procesadas2'][i] = datetime.strptime(y, '%Y-%m-%d') 

2015-08-19
2015-08-06
2016-01-24
2017-01-20
2017-01-20
2016-01-24
2016-01-24
2016-01-24
2017-01-20
2017-01-20
2016-01-24
2015-08-19
2016-01-24
2016-01-24
2017-01-20
2016-01-24
2017-03-12
2016-01-24
2019-03-25
2016-07-19
2017-03-12
2016-01-24
2017-01-20
2016-06-15
2016-01-24
2014-10-20
2016-01-24
2017-03-12
2017-01-20
2017-01-20
2016-01-24
2016-06-15
2016-06-15
2017-03-12
2016-07-19
2017-01-20
2016-01-24
2014-10-20
2015-05-06
2016-01-24
2017-01-20
2016-01-24
2014-10-20
2016-06-15
2016-06-15
2016-07-19
2016-01-24
2017-01-20
2014-10-20
2016-07-19
2016-01-24
2017-03-12
2017-01-20
2016-01-24
2016-01-24
2017-01-20
2016-01-24
2016-06-15
2017-01-20
2016-01-24
2017-03-12
2016-07-19
2017-01-20
2016-01-24
2016-06-15
2014-10-20
2014-10-20
2019-03-25
2016-01-24
2017-01-20
2016-07-19
2017-03-12
2016-01-24
2017-03-12
2016-01-24
2016-07-19
2017-01-20
2016-01-24
2017-01-20
2017-03-12
2016-01-24
2016-07-19
2015-08-19
2015-08-06
2017-03-12
2017-01-20
2016-01-24
2016-01-24
2017-01-20
2017-03-12
2016-01-24

In [64]:
df['fechas_procesadas2'] = np.where(df.fechas_procesadas2.str.contains("/"), \
                                    df['fechas_procesadas2'].replace(' ', '/', regex=True).\
                                    replace('//', '/', regex=True).\
                                    replace('ENERO', '01', regex=True).\
                                    replace('FEBRERO', '02', regex=True).\
                                    replace('MARZO', '03', regex=True).\
                                    replace('ABRIL', '04', regex=True).\
                                    replace('MAYO', '05', regex=True).\
                                    replace('JUNIO', '06', regex=True).\
                                    replace('JULIO', '07', regex=True).\
                                    replace('AGOSTO', '08', regex=True).\
                                    replace('SEPTIEMBRE', '09', regex=True).\
                                    replace('OCTUBRE', '10', regex=True).\
                                    replace('NOVIEMBRE', '11', regex=True).\
                                    replace('DICIEMBRE', '12', regex=True).\
                                    replace('//', '/', regex=True),\
                                    df['fechas_procesadas2'])

In [87]:
df['fechas_procesadas2'] = df['fechas_procesadas2'].astype(str)
for i in range(len(df['fechas_procesadas2'])):
    x = df['fechas_procesadas2'][i]
    counter = x.count('/')
    if (counter == 2 and len(x) == 10) and x[6:10].isnumeric() and x[3:5].isnumeric() and x[0:2].isnumeric():
        y = x[6:10]+"-"+x[3:5]+"-"+x[0:2]
        #print(y)
        df['fechas_procesadas2'][i] = datetime.strptime(y, '%Y-%m-%d') 
        

/home/aide/.pyenv/versions/itam_intro_to_ds/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [66]:
df['fechas_procesadas2'] = df['fechas_procesadas2'].astype(str)
df['fechas_procesadas2'] = np.where(df["fechas_procesadas2"].str.contains(" ")&\
   ~df["fechas_procesadas2"].str.contains("00:00:00"),
                                    df['fechas_procesadas2'].replace(' ', '/', regex=True).\
                                    replace('//', '/', regex=True),\
                                    df['fechas_procesadas2'])

df['fechas_procesadas2'] = df['fechas_procesadas2'].astype(str)
print(sorted(df['fechas_procesadas2'].unique()))

['0/12', '01/06', '018/03/11', '02/DEJULIO/DLE/2018', '02/OCT/2017', '03.08/18', '03/11/20156', '04.04.18', '04/03/16/GLUCOSA/87', '04/ABRIL/2016', '05/0/1/2015', '05/05P/2020', '06.05.15', '06.12.17', '06/08/82010', '07/12', '07/JULIO', '07/JUNIO/2010', '07/JUNIO/2018', '08/JULIO/2011', '08/MARZO/2016', '08/SEP/2020', '09/JUN/2017', '09/NOV/2015', '09/NOV2012', '09/SEP/2016', '1/02/2019', '1/03', '1/03/2019', '1/12', '1/FEBRERO/2019', '1/OCTUBRE/12', '10.06.16', '10/02/14', '10/07/20017', '10/08', '10/09/13', '10/12', '10/ABRIL/2018', '10/AGO/2018', '10/AGOSTO/2018', '10/AL/13', '10/DIC', '10/DIC,/10', '10/DIC/2010', '10/NOV/2011', '10/OCTUBRE/2018', '10/SPTIEMBRE/2019', '11.05.17', '11/04/11', '11/07/13', '11/09/14', '11/11/10', '11/12', '11/NOV./2011', '11/OCT/2018', '12.12.16', '12/06.', '12/06/13', '12/09/14', '12/10001', '12/2021', '120/180', '120/70', '13/05/14', '13/06/14', '13/07/11', '13/08/10', '13/08/14', '13/082010', '13/D/E07/11', '13/DIC/2010', '13/MAYO/2019', '13/SEP/20

In [67]:
df['fechas_procesadas2'] = np.where(df.fechas_procesadas2.str.contains("O"), \
                                    df['fechas_procesadas2'].replace(' ', '/', regex=True).\
                                    replace('//', '/', regex=True).\
                                    replace('//', '/', regex=True),\
                                    df['fechas_procesadas2'])

df['fechas_procesadas2'] = np.where(df.fechas_procesadas2.str.contains("A"), \
                                    df['fechas_procesadas2'].replace(' ', '/', regex=True).\
                                    replace('//', '/', regex=True).\
                                    replace('//', '/', regex=True),\
                                    df['fechas_procesadas2'])

df['fechas_procesadas2'] = np.where(df.fechas_procesadas2.str.contains("E"), \
                                    df['fechas_procesadas2'].replace(' ', '/', regex=True).\
                                    replace('//', '/', regex=True).\
                                    replace('//', '/', regex=True),\
                                    df['fechas_procesadas2'])

df['fechas_procesadas2'] = np.where(df.fechas_procesadas2.str.contains("/"), \
                                    df['fechas_procesadas2'].replace(' ', '/', regex=True).\
                                    replace('./', '/', regex=True).\
                                    replace(',/', '/', regex=True).\
                                    replace('//', '/', regex=True),\
                                    df['fechas_procesadas2'])

In [68]:
df['fechas_procesadas2'] = np.where(df.fechas_procesadas2.str.contains("/"), \
                                    df['fechas_procesadas2'].replace('/ENERO/', '/01/', regex=True).\
                                    replace('/FEBRERO/', '/02/', regex=True).\
                                    replace('/MARZO/', '/03/', regex=True).\
                                    replace('/ABRIL/', '/04/', regex=True).\
                                    replace('/MAYO/', '/05/', regex=True).\
                                    replace('/JUNIO/', '/06/', regex=True).\
                                    replace('/JULIO/', '/07/', regex=True).\
                                    replace('/AGOSTO/', '/08/', regex=True).\
                                    replace('/SEPTIEMBRE/', '/09/', regex=True).\
                                    replace('/OCTUBRE/', '/10/', regex=True).\
                                    replace('/NOVIEMBRE/', '/11/', regex=True).\
                                    replace('/NOV/', '/11/', regex=True).\
                                    replace('/JUN/', '/06/', regex=True).\
                                    replace('/SPTIEMBRE/', '/09/', regex=True).\
                                    replace('/DEIEMBR/', '/12/', regex=True).\
                                    replace('/SEPT/', '/09/', regex=True).\
                                    replace('/SEP/', '/09/', regex=True).\
                                    replace('/FEB/', '/02/', regex=True).\
                                    replace('/ENE/', '/01/', regex=True).\
                                    replace('/DIC/', '/12/', regex=True).\
                                    replace('/OCT/', '/10/', regex=True).\
                                    replace('/AGO/', '/08/', regex=True).\
                                    replace('/JULI/', '/07/', regex=True).\
                                    replace('/JUNI/', '/06/', regex=True).\
                                    replace('/EN/', '/01/', regex=True).\
                                    replace('/AGOST/', '/08/', regex=True).\
                                    replace('/OCTUBR/', '/10/', regex=True).\
                                    replace('/NO/', '/11/', regex=True).\
                                    replace('/MAY/', '/05/', regex=True).\
                                    replace('/SE/', '/09/', regex=True).\
                                    replace('/ABRI/', '/04/', regex=True).\
                                    replace('/EMARZ/', '/03/', regex=True).\
                                    replace('/SPTIEMBR/', '/09/', regex=True).\
                                    replace('/EJULI/', '/07/', regex=True).\
                                    replace('/DI/', '/12/', regex=True).\
                                    replace('/A/', '/08/', regex=True).\
                                    replace('/ENER/', '/01/', regex=True).\
                                    replace('/EENR/', '/01/', regex=True).\
                                    replace('/AGOS/ODE/', '/08/', regex=True).\
                                    replace('/ENERODE/', '/01/', regex=True).\
                                    replace('/FE/', '/02/', regex=True).\
                                    replace('/JU/', '/06/', regex=True).\
                                    replace('/DEJULI/DL/', '/07/', regex=True).\
                                    replace('/MARZ/', '/03/', regex=True).\
                                    replace('/NOV2', '/11/2', regex=True).\
                                    replace('/JUNIO2', '/06/2', regex=True).\
                                    replace('/AG/', '/08/', regex=True).\
                                    replace('/OC/', '/10/', regex=True).\
                                    replace('/FEBRER/', '/02/', regex=True).\
                                    replace('/NER/1Ñ/', '/01/', regex=True).\
                                    replace('/06/DL/', '/06/', regex=True).\
                                    replace('/DICIEMBR/', '/12/', regex=True).\
                                    replace('//', '/', regex=True),\
                                    df['fechas_procesadas2'])

In [69]:
df['fechas_procesadas2'] = np.where(df.fechas_procesadas2.str.contains("\."), \
                                    df['fechas_procesadas2'].replace('\.', '/', regex=True).\
                                    replace('//', '/', regex=True).\
                                    replace('//', '/', regex=True),\
                                    df['fechas_procesadas2'])

In [73]:
df['fechas_procesadas2'] = df['fechas_procesadas2'].astype(str)
for i in range(len(df['fechas_procesadas2'])):
    x = df['fechas_procesadas2'][i]
    counter = x.count('/')
    if (counter == 2 and len(x) == 8) and x[6:8].isnumeric() and x[3:5].isnumeric() and x[0:2].isnumeric():
        y = "20"+x[6:8]+"-"+x[3:5]+"-"+x[0:2]
        #print(y)
        df['fechas_procesadas2'][i] = datetime.strptime(y, '%Y-%m-%d') 
        

/home/aide/.pyenv/versions/itam_intro_to_ds/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [80]:
df['fechas_procesadas2'] = df['fechas_procesadas2'].astype(str)
for i in range(len(df['fechas_procesadas2'])):
    x = df['fechas_procesadas2'][i]
    counter = x.count('/')
    if (counter == 2 and len(x) == 9) and x[5:9].isnumeric() and x[2:4].isnumeric() and x[0:1].isnumeric():
        #print(x)
        if x[0:1] == '0':
            y = x[5:9]+"-"+x[2:4]+"-01"
        else:
            y = x[5:9]+"-"+x[2:4]+"-0"+x[0:1]
        #print(y)
        df['fechas_procesadas2'][i] = datetime.strptime(y, '%Y-%m-%d') 

/home/aide/.pyenv/versions/itam_intro_to_ds/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':


In [85]:
df['fechas_procesadas2'] = df['fechas_procesadas2'].astype(str)
for i in range(len(df['fechas_procesadas2'])):
    x = df['fechas_procesadas2'][i]
    counter = x.count('/')
    if (counter == 2 and len(x) == 7) and x[5:7].isnumeric() and x[2:4].isnumeric() and x[0:1].isnumeric():
        a = ""
        if(int(x[5:7])>22):
            a = "19"
        else:
            a = "20"
        #print(x)
        if x[0:1] == '0':
            y = a+x[5:7]+"-"+x[2:4]+"-01"
        else:
            y = a+x[5:7]+"-"+x[2:4]+"-0"+x[0:1]
        #print(y)
        df['fechas_procesadas2'][i] = datetime.strptime(y, '%Y-%m-%d') 

/home/aide/.pyenv/versions/itam_intro_to_ds/lib/python3.7/site-packages/ipykernel_launcher.py:17: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


In [93]:
df['fechas_procesadas2'] = df['fechas_procesadas2'].astype(str)
for i in range(len(df['fechas_procesadas2'])):
    x = df['fechas_procesadas2'][i]
    counter = x.count('/')
    if (counter == 2 and len(x) == 8) and x[4:8].isnumeric() and x[1:3].isnumeric() and x[0:1] == '/':
        #print(x)
        y = x[4:8]+"-"+x[1:3]+"-01"
        #print(y)
        df['fechas_procesadas2'][i] = datetime.strptime(y, '%Y-%m-%d') 

/home/aide/.pyenv/versions/itam_intro_to_ds/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':


In [89]:
df['fechas_procesadas2'] = df['fechas_procesadas2'].replace('UMF82', np.nan, regex=True)
df['fechas_procesadas2'] = df['fechas_procesadas2'].replace('20BR-/-/', np.nan, regex=True)
df['fechas_procesadas2'] = df['fechas_procesadas2'].replace('3/0/20156', np.nan, regex=True)
df['fechas_procesadas2'] = df['fechas_procesadas2'].replace('3/08/GLUCMEIA', np.nan, regex=True)
df['fechas_procesadas2'] = df['fechas_procesadas2'].replace('37/00', np.nan, regex=True)
df['fechas_procesadas2'] = df['fechas_procesadas2'].replace('0/0/1/GLUCOS/87', np.nan, regex=True)
df['fechas_procesadas2'] = df['fechas_procesadas2'].replace('1/0/DLE2019', np.nan, regex=True)

In [101]:
select_values = ['/0/10', '/0/11', '/0/13', '/0/14', '/0/17', '/0/18', '/0/2010', '/0/2014', 
'/0/2015', '/0/2016', '/0/2017', 
 '/0/2018', '/0/2019', '/0/2021', '/03', '/07', '/1/2016', '/10/12', '/12', '/DE', '/DICIEMBR/2014', '/SEP', 
 '/SEPT', '0/0/82010', '0/06', '0/1/20156', '0/12', '0/2015', '0/JULIO', '01/0/11', '03/0/18', '1/0/10', 
 '1/0/11', '1/0/13', '1/0/14', '1/0/17', '1/0/20017', '1/0/2020188/3', '1/0/21', '1/0/DLE2019', '1/03', 
 '1/05', '1/06', '1/06/', '1/07', '1/08', '1/082010', '1/09/2016--', '1/1/10', '1/1/13', '1/1/14', '1/10001', 
 '1/12', '1/12/2015/-', '1/2021', '1/4', '1/DIC', '1/E0/11', '1/NOV', '12/180', '12/70', '2/0/09', '2/0/10', 
 '2/0/12', '2/0/14', '2/0/18', '2/0/201/3/08', '2/0/2019,SIN', '2/0/2019---', '2/0/21/-', '2/01', '2/03', 
 '2/03/', '2/05', '2/072019', '2/08', '2/1/13', '2/12/DRA', '2/2-EP-/', '2/20', '2/2012', '2/60', '2/NOV', 
 '2/OCUTBRE', '2/SEP', '3/0/18', '31-12-2019-', '37/22', 'ABRI/21', 'AGIST/2017', 'DEIEMBR/2008', 'FEBRER/21', 
 'JUNI/2016/-', 'MASRZ/2016', 'NAN', 'SE/2018', 'SEP', 'nan']
df_cut = df.query('fechas_procesadas2 in @select_values')
print(sorted(df_cut.fechas_procesadas2.unique()))

['/0/10', '/0/11', '/0/13', '/0/14', '/0/17', '/0/18', '/0/2010', '/0/2014', '/0/2015', '/0/2016', '/0/2017', '/0/2018', '/0/2019', '/0/2021', '/03', '/07', '/1/2016', '/10/12', '/12', '/DE', '/DICIEMBR/2014', '/SEP', '/SEPT', '0/0/82010', '0/06', '0/1/20156', '0/12', '0/2015', '0/JULIO', '01/0/11', '03/0/18', '1/0/10', '1/0/11', '1/0/13', '1/0/14', '1/0/17', '1/0/20017', '1/0/2020188/3', '1/0/21', '1/0/DLE2019', '1/03', '1/05', '1/06', '1/06/', '1/07', '1/08', '1/082010', '1/09/2016--', '1/1/10', '1/1/13', '1/1/14', '1/10001', '1/12', '1/12/2015/-', '1/2021', '1/4', '1/DIC', '1/E0/11', '1/NOV', '12/180', '12/70', '2/0/09', '2/0/10', '2/0/12', '2/0/14', '2/0/18', '2/0/201/3/08', '2/0/2019,SIN', '2/0/2019---', '2/0/21/-', '2/01', '2/03', '2/03/', '2/05', '2/072019', '2/08', '2/1/13', '2/12/DRA', '2/2-EP-/', '2/20', '2/2012', '2/60', '2/NOV', '2/OCUTBRE', '2/SEP', '3/0/18', '31-12-2019-', '37/22', 'ABRI/21', 'AGIST/2017', 'DEIEMBR/2008', 'FEBRER/21', 'JUNI/2016/-', 'MASRZ/2016', 'NAN', '

In [105]:
df['fechas_procesadas2'] = np.where(df['fechas_procesadas2'].isin(['/0/10', '/0/11', '/0/13', '/0/14', '/0/17', 
'/0/18', '/0/2010', '/0/2014', '/0/2015', '/0/2016', '/0/2017', '/0/2018', '/0/2019', '/0/2021', '/03', '/07', 
'/1/2016', '/10/12', '/12', '/DE', '/DICIEMBR/2014', '/SEP', '/SEPT', '0/0/82010', '0/06', '0/1/20156', '0/12', 
'0/2015', '0/JULIO', '01/0/11', '03/0/18', '1/0/10', '1/0/11', '1/0/13', '1/0/14', '1/0/17', '1/0/20017', 
'1/0/2020188/3', '1/0/21', '1/0/DLE2019', '1/03', '1/05', '1/06', '1/06/', '1/07', '1/08', '1/082010', 
'1/09/2016--', '1/1/10', '1/1/13', '1/1/14', '1/10001', '1/12', '1/12/2015/-', '1/2021', '1/4', '1/DIC', 
'1/E0/11', '1/NOV', '12/180', '12/70', '2/0/09', '2/0/10', '2/0/12', '2/0/14', '2/0/18', '2/0/201/3/08', 
'2/0/2019,SIN', '2/0/2019---', '2/0/21/-', '2/01', '2/03', '2/03/', '2/05', '2/072019', '2/08', '2/1/13', 
'2/12/DRA', '2/2-EP-/', '2/20', '2/2012', '2/60', '2/NOV', '2/OCUTBRE', '2/SEP', '3/0/18', '31-12-2019-', 
'37/22', 'ABRI/21', 'AGIST/2017', 'DEIEMBR/2008', 'FEBRER/21', 'JUNI/2016/-', 'MASRZ/2016', 'NAN', 'SE/2018', 
'SEP', 'nan']), np.nan, df['fechas_procesadas2'])

In [106]:
df['fechas_procesadas2'] = df['fechas_procesadas2'].astype(str)
print(sorted(df['fechas_procesadas2'].unique()))

['1987-09-01 00:00:00', '2004-11-05 00:00:00', '2007-06-02 00:00:00', '2008-12-02 00:00:00', '2009-02-08 00:00:00', '2009-06-01 00:00:00', '2009-06-12 00:00:00', '2009-09-10 00:00:00', '2009-10-13 00:00:00', '2009-12-02 00:00:00', '2009-12-23 00:00:00', '2010-02-02 00:00:00', '2010-02-10 00:00:00', '2010-05-24 00:00:00', '2010-05-31 00:00:00', '2010-06-01 00:00:00', '2010-06-29 00:00:00', '2010-07-02 00:00:00', '2010-07-22 00:00:00', '2010-08-02 00:00:00', '2010-09-01 00:00:00', '2010-09-08 00:00:00', '2010-09-27 00:00:00', '2010-10-01 00:00:00', '2010-10-22 00:00:00', '2010-10-28 00:00:00', '2010-11-01 00:00:00', '2010-12-01 00:00:00', '2010-12-14 00:00:00', '2010-12-20 00:00:00', '2011-01-01 00:00:00', '2011-01-18 00:00:00', '2011-02-14 00:00:00', '2011-02-15 00:00:00', '2011-03-10 00:00:00', '2011-03-13 00:00:00', '2011-04-01 00:00:00', '2011-04-14 00:00:00', '2011-04-27 00:00:00', '2011-05-29 00:00:00', '2011-06-09 00:00:00', '2011-07-01 00:00:00', '2011-07-08 00:00:00', '2011-08-1

In [72]:
print(np.where(contain_values.hba1c.str.contains("/"), \
               contain_values['hba1c'],\
               contain_values['presion_arterial']))

NameError: name 'contain_values' is not defined

In [ ]:
df['fecha_nacimiento'] = pd.to_datetime(df['fecha_nacimiento']).dt.date
df.fecha_nacimiento.unique()

In [ ]:
df['fecha_consulta'] = pd.to_datetime(df['fecha_consulta']).dt.date
df.fecha_consulta.unique()

In [ ]:
df.head

In [ ]:
prop_codigo = df.groupby(['newid'], as_index=False)['cx_curp']\
.count()\
.rename(columns={'cx_curp': 'count'})
prop_codigo['prop'] = prop_codigo['count']/np.sum(prop_codigo['count'])
prop_codigo.sort_values(by = ['prop'], ascending = False)

In [ ]:
prop_codigo = df.groupby(['cx_curp'], as_index=False)['newid']\
.count()\
.rename(columns={'newid': 'count'})
prop_codigo['prop'] = prop_codigo['count']/np.sum(prop_codigo['count'])
prop_codigo.sort_values(by = ['prop'], ascending = False)

# EDA